### ISSUE TITLE
Support for DAC output Voltage control 0-3.3V

### ISSUE THREAD

**Issue by xal88** [toitware/public#24] opened 2021-10-14 19:36 UTC
**Is your feature request related to a problem? Please describe.**
Many devices can be controlled via a 0-10V output signal ( e.g. Ventilation systems like LUNOS or proportional heating valves ).
ESP32 has 2 internal DACs ( PIN 25 and 26 )
This Voltage can easily amplified via OP ( LM358 has 2 circuits ) to 0-10V.  

**Describe the solution you'd like**
**gpio** should have  a dac option.
> DAC2 ::= gpio.Dac (gpio.Pin.out _26)
> DAC2.set x      
with x in range (0,255) for output 0-3.3V

Alternative with PWM output needs more hardware to bring to 0-10V. ( and is also not supported in TOIT)

As the ESP32 has 2 DACs, both should be supported simultaniously.

Thanks for considering this feature 👍

**Comment by floitsch** [comment] 2022-03-08 11:23
Duplicate of https://github.com/toitlang/toit/issues/204

**Closed as completed by floitsch** 2022-03-08 11:23 UTC
Labels: enhancement
